# Generated by Django 3.1.7 on 2021-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210707_1512'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartiteam',
            new_name='Cartitem',
        ),
    ]
