# Generated by Django 3.1.7 on 2021-07-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_catergory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
